dist: bionic
language: python
python:
  - "3.7"

notifications:
  irc: "chat.freenode.net#london-hack-space-infrastructure"
  
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script: python manage.py test