# Docker Compose file for acserver

services:
  server:
    build:
      context: .
      target: server-build
    volumes:
      - ./:/server
    command: bash runserver.sh
    restart: on-failure
    ports:
      - 0.0.0.0:${PORT:-8000}:8000
