version: '3.8'
services:

  python:
    build:
      context: .
      dockerfile: docker/Dockerfile-python
    environment:
      DJANGO_SETTINGS_MODULE: acserver.settings
    ports:
      - 9002:9002
    volumes:
      - .:/app:z
    depends_on:
      - db
    networks:
      - acserver

  db:
    image: "mysql"
    environment:
      MYSQL_ROOT_PASSWORD: acserver
      MYSQL_DATABASE: acserver
      MYSQL_USER: acserver
      MYSQL_PASSWORD: acserver
    ports:
      - 13306:3306
    volumes:
      - mysqldata-acserver:/var/lib/myqsl
    networks:
      - acserver

  syslog:
    build:
      context: .
      dockerfile: docker/Dockerfile-syslog
    ports:
      - 514:514/udp
      - 514:514/tcp
    volumes:
      - acserver-syslog-logs:/opt/syslog
      - ./etc/rsyslog.conf:/etc/rsyslog.conf
    networks:
      - acserver

volumes:
  mysqldata-acserver:
  acserver-syslog-logs:

networks:
  acserver:

