FROM debian:jessie
# FROM python:3.9

RUN apt-get update && \
    apt-get -y install \
      libldap2-dev \
      libpq-dev \
      libsasl2-dev \
      postgresql-client \
      python3-dev \
      python3-pip \
      vim \
      virtualenv

WORKDIR /app

RUN ls
# RUN python3 -m venv /opt/venv
RUN virtualenv -p python3 /opt/venv

# last version which supports python 3.4
RUN . /opt/venv/bin/activate && pip install --upgrade pip==19.1.1

COPY requirements-docker-jessie.txt requirements.txt
RUN . /opt/venv/bin/activate && pip install -r requirements.txt

COPY . .

EXPOSE 9002

CMD ["docker/python-dev-init.sh"]

