# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-28 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_auto_20180801_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='type',
            field=models.IntegerField(choices=[(1, 'Unrestricted Door'), (2, 'Restricted Door'), (3, 'Tool')], default=3),
        ),
    ]
