# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-28 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_tool_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gladosfile',
            field=models.TextField(blank=True),
        ),
    ]
