# Generated by Django 2.2.20 on 2021-04-24 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_user_gladosfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='mqtt_name',
            field=models.TextField(blank=True, help_text='The MQTT name of the node. This is the second part of the path.\n                        "Not used by ACServer directly, but appears in API responses'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='server.Tool'),
        ),
    ]
