# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-03 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_user_gladosfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('stock', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VendItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('price', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='machineitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.VendItem'),
        ),
        migrations.AddField(
            model_name='machineitem',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Tool'),
        ),
    ]
