# Generated by Django 3.2.25 on 2024-10-28 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_auto_20210424_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='mqtt_name',
            field=models.TextField(blank=True, help_text='The MQTT name of the node. This is the second part of the path.\n                        "Not used by ACServer directly, but appears in API responses.\n                        This does NOT include the door/ or tool/ prefix - that can be implied\n                        from the tool type'),
        ),
    ]
