# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-07 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_auto_20190203_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='balance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
