# Generated by Django 3.2.25 on 2024-10-28 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0013_user_ldap'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='nickname',
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('id', 'nickname')},
        ),
    ]
