# Generated by Django 3.2.25 on 2024-11-01 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0014_auto_20241028_0207'),
    ]

    def copy_name_from_nick(apps, schema_editor):
        User = apps.get_model('server', 'user')
        for user in User.objects.all():
            user.name = user.nickname
            user.save()

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.RunPython(copy_name_from_nick),
    ]
